version: '3.7'

services:

# ---------------[ Web Server Frontend service ]------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    env_file:
      - ./frontend/.env.production
    expose:
      - '8101'
    ports:
      - '8101:8101'
    command: ["http-server", "./dist", "-p", "8101"]
    depends_on:
      - backend

# ---------------[ Web Server Backend service ]------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      - PERFORMANCES_RECORD_PATH=$BACKEND_PERFORMANCES_RECORD_PATH
    env_file:
      - ./backend/.production.env
    volumes:
      - ./shared:/src
      - ./analysis:/analysis
    expose:
      - '8100'
    ports:
      - '8100:8100'
    command: ["yarn", "run", "start"]

# ---------------[ Compiler service ]------------------
  compiler:
    build:
      context: ./compiler
      dockerfile: Dockerfile.production
    env_file:
      - ./compiler/.production.env
    volumes:
      - ./shared:/src
      - ./analysis:/analysis
    ports:
      - '8102:8102'
    command: ["yarn", "run", "start"]
    depends_on:
      - backend