version: '3.7'

services:
  # Frontend container configuration (vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/home/vue/app
      - frontend_node_modules:/home/vue/app/node_modules
    expose:
      - '8080'
    ports:
      - '8081:8080'
    command: ["yarn", "run", "serve"]
    depends_on:
      - backend
    networks:
      - web-net
  # Backend container configuration (node.js)
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/home/node/app
      - ./shared:/src
      - backend_node_modules:/home/vue/app/node_modules
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: ["yarn", "run", "dev"]
    depends_on:
      - redis-smq
    networks:
      - web-net
      - compiler-net
  # Compiler container configuration (node.js)
  compiler:
    build:
      context: ./compiler
    env_file:
      - ./compiler/.development.env
    volumes:
      - ./compiler:/home/node/app
      - ./shared:/src
      - compiler_node_modules:/home/vue/app/node_modules
    command: ["yarn", "run", "dev"]
    networks:
      - compiler-net
    depends_on:
      - redis-smq
      - backend
  # Redis container configuration (redis)
  redis-smq:
    image: 'redis:alpine'
    networks:
      - compiler-net

volumes:
  compiler_node_modules:
  frontend_node_modules:
  backend_node_modules:

networks:
  web-net:
    driver: bridge
  compiler-net:
    driver: bridge
    internal: true