version: '3.7'

services:

# ---------------[ Web Server Frontend service ]------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/home/vue/app
      - /home/vue/app/node_modules
      # node_modules need to be mounted as a separate volume because otherwise local (hosting environment) node_modules will be used
      # and if the hosting environment is not the same as the one used to build the image, the node_modules can throw compatibility errors.
      # also: if the local node_modules are empty, the node_modules builded during the image build will be overwritten by the empty local node_modules,
      # since the local directory (./frontend) is mounted as a volume AFTER the build, overwriting everything in '/home/vue/app'.
    expose:
      - '8080'
    ports:
      - '8081:8080'
    command: ["yarn", "run", "serve"]
    depends_on:
      - backend
    networks:
      - web-net
# ---------------[ Web Server Backend service ]------------------
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.development.env
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
      - ./shared:/src
    ports:
      - "8080:80"
    command: ["yarn", "run", "dev"]
    networks:
      - web-net
      - compiler-net
# ---------------[ Compiler service ]------------------
  compiler:
    build:
      context: ./compiler
    env_file:
      - ./compiler/.development.env
    volumes:
      - ./compiler:/home/node/app
      - /home/node/app/node_modules
      - ./shared:/src
    ports:
      - "8082:82"
    command: ["yarn", "run", "dev"]
    networks:
      - compiler-net
    depends_on:
      - backend

networks:
# ---------------[ Web Server Network ]----------------
  web-net:
    driver: bridge
# ---------------[ Compiler Network ]------------------
  compiler-net:
    driver: bridge
    internal: true