version: '3.7'

services:
  backend:
    container_name: svc-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/home/node/app
      - ./shared:/src
    expose:
      - '8080'
    ports:
      - '8080:80'
    command: ["yarn", "run", "dev"]
    depends_on:
      - compiler
    networks:
      - web-net
      - compiler-net
  compiler:
    container_name: svc-compiler
    build:
      context: ./compiler
      dockerfile: ./Dockerfile
    ports:
      - '1377:1377'
    volumes:
      - ./compiler:/home/node/app
      - ./shared:/src
    command: ["yarn", "run", "dev"]
    networks:
      - compiler-net

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: ./shared

networks:
  web-net:
    driver: bridge
  compiler-net:
    driver: bridge
    internal: true