version: '3.7'

services:
  backend:
    container_name: svc-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/home/node/app
      - ./shared:/src
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: ["yarn", "run", "prod"]
    depends_on:
      - compiler
    networks:
      - svc-web-net
      - svc-compiler-net
  compiler:
    container_name: svc-compiler
    build:
      context: ./compiler
      dockerfile: ./Dockerfile
    ports:
      - '1377:1377'
    volumes:
      - ./compiler:/home/node/app
      - ./shared:/src
    command: ["yarn", "run", "prod"]
    networks:
      - svc-compiler-net

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: ./shared

networks:
  web-net:
    driver: bridge
  compiler-net:
    driver: bridge
    internal: true