version: '3.7'

services:
  svc-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/home/node/app
      - ./shared:/src
    container_name: svc-backend
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - svc-compiler
  svc-compiler:
    build:
      context: ./compiler
      dockerfile: ./Dockerfile
    expose:
      - '1377'
    ports:
      - '1377:1377'
    volumes:
      - ./compiler:/home/node/app
      - ./shared:/src
    container_name: svc-compiler
    command: ["tail", "-f", "/dev/null"]

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: ./shared