tsung:
  ip: "34.65.207.218" # "localhost"
  config_file: http_simple.xml
  log_dir: "results/"

  configs:
    new1:
      params:
        interarrival: 5
        max_jobs: 20
    new2:
      params:
        interarrival: 1
        max_jobs: 20
    new3:
      params:
        interarrival: 0.1
        max_jobs: 20
    new4:
      params:
        interarrival: 0.07
        max_jobs: 20

    # ------------------------------- #
    test1:
      params:
        interarrival: 0.1
        max_jobs: 10
      result:
        service_rate: 9.83
        max_jobs_reached: 7
    test2:
      params:
        interarrival: 0.1
        max_jobs: 50
    test3:
      params:
        interarrival: 0.1
        max_jobs: 100
    test4:
      params:
        interarrival: 0.1
        max_jobs: 500

    # ------------------------------- #
    test5:
      params:
        interarrival: 0.05
        max_jobs: 10
      result:
        service_rate: 18.97
        max_jobs_reached: 10
    test6:
      params:
        interarrival: 0.05
        max_jobs: 50
    test7:
      params:
        interarrival: 0.05
        max_jobs: 100
      result:
        service_rate: 18.96
        max_jobs_reached: 100
    test8:
      params:
        interarrival: 0.05
        max_jobs: 500
      result:
        service_rate: 19.48
        max_jobs_reached: 500

    # ------------------------------- #
    test9:
      params:
        interarrival: 0.03
        max_jobs: 10
    test10:
      params:
        interarrival: 0.03
        max_jobs: 50
    test11:
      params:
        interarrival: 0.03
        max_jobs: 100
    test12:
      params:
        interarrival: 0.03
        max_jobs: 500

    # ------------------------------- #
    test13:
      params:
        interarrival: 0.07
        max_jobs: 30
      result:
        service_rate: 13.63
        max_jobs_reached: 30
