name: trigger jenkins compilation
on: [push]
jobs:
  # force deploy
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger jenkins job
      uses: jabbukka/jenkins-trigger@main
      with:
        url: ${{ secrets.JENKINS_URL }}
        job_name: "svc"
        user_name: ${{ secrets.JENKINS_DEPLOY_USER }}
        api_token: ${{ secrets.JENKINS_DEPLOY_TOKEN }}
        wait: "true"
        timeout: "1000"
        parameter: "{\"build\":\"true\"}"
